# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockband', '0002_came_here_to_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='rockband.Band'),
        ),
    ]
