# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_time', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
