# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='raw_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
